/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/sculpture_3.glb -o components/Sculpture3.jsx -r public -k
Author: The Smithsonian Institution (https://sketchfab.com/Smithsonian)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/george-washington-greenough-statue-1840-6f90971e3eb24c0b8091086242f2c3b3
Title: George Washington Greenough Statue (1840)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { DissolveMaterial } from "./DissolveMaterial";
import { useFrame } from "@react-three/fiber";

export function Sculpture3(props) {
  const { nodes, materials } = useGLTF("/models/sculpture_3.glb");

  const ref = useRef();

  useFrame(() => {
    ref.current.visible = props.progress.current !== 0;
  });

  return (
    <group ref={ref} scale={0.00025} {...props} dispose={null}>
      <mesh
        name="Object_4"
        geometry={nodes.Object_4.geometry}
        material={materials["default"]}
      >
        <DissolveMaterial
          baseMaterial={materials["default"]}
          visible={props.dissolveVisible}
          color="#7f532f"
          progress={props.progress}
        />
      </mesh>
      <mesh
        name="Object_5"
        geometry={nodes.Object_5.geometry}
        material={materials["default"]}
      >
        <DissolveMaterial
          baseMaterial={materials["default"]}
          visible={props.dissolveVisible}
          color="#7f532f"
          progress={props.progress}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/sculpture_3.glb");
