/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/sculpture_2.glb -o components/Sculpture2.jsx -r public -k
Author: The Smithsonian Institution (https://sketchfab.com/Smithsonian)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/figure-of-a-dancer-63212acff8474095ba2626d9366df852
Title: Figure of a Dancer
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { DissolveMaterial } from "./DissolveMaterial";

export function Sculpture2(props) {
  const { nodes, materials } = useGLTF("/models/sculpture_2.glb");
  return (
    <group scale={0.5} {...props} dispose={null}>
      <mesh
        name="Object_4"
        geometry={nodes.Object_4.geometry}
        material={materials["default"]}
        scale={0.004}
      >
        {/* <DissolveMaterial
          baseMaterial={materials["default"]}
          visible={props.dissolveVisible}
          color="#7f532f"
          progress={props.progress}
        /> */}
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/sculpture_2.glb");
