/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/sculpture_1.glb -o components/Sculpture1.jsx -r public -k
Author: 3dhdscan (https://sketchfab.com/3dhdscan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fountain-with-three-putts-brno-luzanky-430b9e5354484860b8b41505e9b63298
Title: Fountain with three putts, Brno Lužánky
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Sculpture1(props) {
  const { nodes, materials } = useGLTF("/models/sculpture_1.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        position={[-545.733, -227.051, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.026}
      >
        <group name="kasna_luzankyFBX" rotation={[-Math.PI, 0, 0]}>
          <group
            name="kasna_luzanky"
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              name="kasna_luzanky_kasna_luzanky_0"
              geometry={nodes.kasna_luzanky_kasna_luzanky_0.geometry}
              material={materials.kasna_luzanky}
            />
            <mesh
              name="kasna_luzanky_kasna_luzanky_0_1"
              geometry={nodes.kasna_luzanky_kasna_luzanky_0_1.geometry}
              material={materials.kasna_luzanky}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/sculpture_1.glb");
