/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/sculpture_4.glb -o components/Sculpture4.jsx -r public -k
Author: The Smithsonian Institution (https://sketchfab.com/Smithsonian)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/figure-of-a-dancer-63212acff8474095ba2626d9366df852
Title: Figure of a Dancer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { DissolveMaterial } from "./DissolveMaterial";
import { useFrame } from "@react-three/fiber";

export function Sculpture4(props) {
  const { nodes, materials } = useGLTF("/models/sculpture_4.glb");

  const ref = useRef();

  useFrame(() => {
    ref.current.visible = props.progress.current !== 0;
  });

  return (
    <group ref={ref} scale={0.5} {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.004}
      >
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="Object_4"
            geometry={nodes.Object_4.geometry}
            material={materials["default"]}
          >
            <DissolveMaterial
              baseMaterial={materials["default"]}
              visible={props.dissolveVisible}
              color="#7f532f"
              progress={props.progress}
            />
          </mesh>
          <mesh
            name="Object_5"
            geometry={nodes.Object_5.geometry}
            material={materials["default"]}
          >
            <DissolveMaterial
              baseMaterial={materials["default"]}
              visible={props.dissolveVisible}
              color="#7f532f"
              progress={props.progress}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/sculpture_4.glb");
