/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/stone.glb -o components/Stone.jsx -r public -k
Boulder by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/3jql0qtape-)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useExplode } from "@/hooks/useExplode";

export function Stone(props) {
  const group = useRef();

  useExplode(group, {
    distance: 6,
    progress: props.progress
  });

  const { nodes, materials } = useGLTF("/models/stone.glb");
  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        name="origin"
        geometry={nodes.origin.geometry}
        material={materials.None}
      />
      <mesh
        name="boulder_cell"
        geometry={nodes.boulder_cell.geometry}
        material={materials.None}
        position={[-0.258, 0.291, -0.529]}
      />
      <mesh
        name="boulder_cell001"
        geometry={nodes.boulder_cell001.geometry}
        material={materials.None}
        position={[-0.346, 0.444, -0.119]}
      />
      <mesh
        name="boulder_cell003"
        geometry={nodes.boulder_cell003.geometry}
        material={materials.None}
        position={[0.337, 0.385, 0.294]}
      />
      <mesh
        name="boulder_cell004"
        geometry={nodes.boulder_cell004.geometry}
        material={materials.None}
        position={[-0.186, -0.496, 0.25]}
      />
      <mesh
        name="boulder_cell006"
        geometry={nodes.boulder_cell006.geometry}
        material={materials.None}
        position={[-0.051, 0.402, -0.415]}
      />
      <mesh
        name="boulder_cell008"
        geometry={nodes.boulder_cell008.geometry}
        material={materials.None}
        position={[0.009, 0.303, -0.576]}
      />
      <mesh
        name="boulder_cell009"
        geometry={nodes.boulder_cell009.geometry}
        material={materials.None}
        position={[-0.296, 0.471, 0.254]}
      />
      <mesh
        name="boulder_cell010"
        geometry={nodes.boulder_cell010.geometry}
        material={materials.None}
        position={[-0.446, -0.131, -0.116]}
      />
      <mesh
        name="boulder_cell011"
        geometry={nodes.boulder_cell011.geometry}
        material={materials.None}
        position={[0.029, -0.532, 0.066]}
      />
      <mesh
        name="boulder_cell013"
        geometry={nodes.boulder_cell013.geometry}
        material={materials.None}
        position={[0.258, -0.178, 0.171]}
      />
      <mesh
        name="boulder_cell014"
        geometry={nodes.boulder_cell014.geometry}
        material={materials.None}
        position={[-0.073, 0.104, 0.556]}
      />
      <mesh
        name="boulder_cell015"
        geometry={nodes.boulder_cell015.geometry}
        material={materials.None}
        position={[-0.474, -0.193, 0.403]}
      />
      <mesh
        name="boulder_cell016"
        geometry={nodes.boulder_cell016.geometry}
        material={materials.None}
        position={[-0.261, 0.078, -0.633]}
      />
      <mesh
        name="boulder_cell017"
        geometry={nodes.boulder_cell017.geometry}
        material={materials.None}
        position={[-0.101, 0.316, 0.456]}
      />
      <mesh
        name="boulder_cell018"
        geometry={nodes.boulder_cell018.geometry}
        material={materials.None}
        position={[-0.192, -0.094, 0.549]}
      />
      <mesh
        name="boulder_cell019"
        geometry={nodes.boulder_cell019.geometry}
        material={materials.None}
        position={[-0.182, 0.557, 0.207]}
      />
      <mesh
        name="boulder_cell020"
        geometry={nodes.boulder_cell020.geometry}
        material={materials.None}
        position={[0.346, 0.519, -0.186]}
      />
      <mesh
        name="boulder_cell022"
        geometry={nodes.boulder_cell022.geometry}
        material={materials.None}
        position={[-0.302, -0.033, 0.455]}
      />
      <mesh
        name="boulder_cell025"
        geometry={nodes.boulder_cell025.geometry}
        material={materials.None}
        position={[-0.105, 0.583, -0.317]}
      />
      <mesh
        name="boulder_cell026"
        geometry={nodes.boulder_cell026.geometry}
        material={materials.None}
        position={[0.458, 0.23, 0.248]}
      />
      <mesh
        name="boulder_cell027"
        geometry={nodes.boulder_cell027.geometry}
        material={materials.None}
        position={[0.256, -0.594, 0.111]}
      />
      <mesh
        name="boulder_cell028"
        geometry={nodes.boulder_cell028.geometry}
        material={materials.None}
        position={[-0.026, -0.046, -0.68]}
      />
      <mesh
        name="boulder_cell029"
        geometry={nodes.boulder_cell029.geometry}
        material={materials.None}
        position={[-0.59, 0.063, 0.314]}
      />
      <mesh
        name="boulder_cell030"
        geometry={nodes.boulder_cell030.geometry}
        material={materials.None}
        position={[-0.263, -0.116, -0.386]}
      />
      <mesh
        name="boulder_cell031"
        geometry={nodes.boulder_cell031.geometry}
        material={materials.None}
        position={[0.307, -0.144, -0.386]}
      />
      <mesh
        name="boulder_cell032"
        geometry={nodes.boulder_cell032.geometry}
        material={materials.None}
        position={[0.367, -0.407, -0.185]}
      />
      <mesh
        name="boulder_cell033"
        geometry={nodes.boulder_cell033.geometry}
        material={materials.None}
        position={[0.11, 0.454, 0.346]}
      />
      <mesh
        name="boulder_cell034"
        geometry={nodes.boulder_cell034.geometry}
        material={materials.None}
        position={[-0.517, 0.043, 0.428]}
      />
      <mesh
        name="boulder_cell035"
        geometry={nodes.boulder_cell035.geometry}
        material={materials.None}
        position={[-0.184, -0.489, 0.001]}
      />
      <mesh
        name="boulder_cell036"
        geometry={nodes.boulder_cell036.geometry}
        material={materials.None}
        position={[-0.503, 0.425, 0.236]}
      />
      <mesh
        name="boulder_cell037"
        geometry={nodes.boulder_cell037.geometry}
        material={materials.None}
        position={[0.153, 0.17, 0.443]}
      />
      <mesh
        name="boulder_cell039"
        geometry={nodes.boulder_cell039.geometry}
        material={materials.None}
        position={[-0.248, -0.6, 0.017]}
      />
      <mesh
        name="boulder_cell040"
        geometry={nodes.boulder_cell040.geometry}
        material={materials.None}
        position={[0.427, -0.496, 0.183]}
      />
      <mesh
        name="boulder_cell041"
        geometry={nodes.boulder_cell041.geometry}
        material={materials.None}
        position={[0.453, -0.453, 0.052]}
      />
      <mesh
        name="boulder_cell043"
        geometry={nodes.boulder_cell043.geometry}
        material={materials.None}
        position={[0.182, -0.458, 0.37]}
      />
      <mesh
        name="boulder_cell044"
        geometry={nodes.boulder_cell044.geometry}
        material={materials.None}
        position={[-0.425, -0.475, 0.064]}
      />
      <mesh
        name="boulder_cell046"
        geometry={nodes.boulder_cell046.geometry}
        material={materials.None}
        position={[-0.315, 0.185, 0.231]}
      />
      <mesh
        name="boulder_cell047"
        geometry={nodes.boulder_cell047.geometry}
        material={materials.None}
        position={[0.384, 0.419, 0.1]}
      />
      <mesh
        name="boulder_cell049"
        geometry={nodes.boulder_cell049.geometry}
        material={materials.None}
        position={[-0.038, 0.028, -0.52]}
      />
      <mesh
        name="boulder_cell050"
        geometry={nodes.boulder_cell050.geometry}
        material={materials.None}
        position={[-0.347, -0.229, 0.216]}
      />
      <mesh
        name="boulder_cell051"
        geometry={nodes.boulder_cell051.geometry}
        material={materials.None}
        position={[0.541, -0.256, -0.1]}
      />
      <mesh
        name="boulder_cell052"
        geometry={nodes.boulder_cell052.geometry}
        material={materials.None}
        position={[0.175, 0.435, -0.369]}
      />
      <mesh
        name="boulder_cell053"
        geometry={nodes.boulder_cell053.geometry}
        material={materials.None}
        position={[0.387, 0.179, -0.07]}
      />
      <mesh
        name="boulder_cell054"
        geometry={nodes.boulder_cell054.geometry}
        material={materials.None}
        position={[0.229, 0.107, -0.486]}
      />
      <mesh
        name="boulder_cell055"
        geometry={nodes.boulder_cell055.geometry}
        material={materials.None}
        position={[-0.103, -0.29, 0.437]}
      />
      <mesh
        name="boulder_cell056"
        geometry={nodes.boulder_cell056.geometry}
        material={materials.None}
        position={[0.023, 0.401, -0.018]}
      />
      <mesh
        name="boulder_cell057"
        geometry={nodes.boulder_cell057.geometry}
        material={materials.None}
        position={[-0.244, -0.187, -0.611]}
      />
      <mesh
        name="boulder_cell058"
        geometry={nodes.boulder_cell058.geometry}
        material={materials.None}
        position={[0.093, -0.177, 0.472]}
      />
      <mesh
        name="boulder_cell059"
        geometry={nodes.boulder_cell059.geometry}
        material={materials.None}
        position={[-0.11, 0.169, -0.672]}
      />
      <mesh
        name="boulder_cell060"
        geometry={nodes.boulder_cell060.geometry}
        material={materials.None}
        position={[0.138, -0.591, 0.277]}
      />
      <mesh
        name="boulder_cell061"
        geometry={nodes.boulder_cell061.geometry}
        material={materials.None}
        position={[-0.362, 0.618, 0.017]}
      />
      <mesh
        name="boulder_cell062"
        geometry={nodes.boulder_cell062.geometry}
        material={materials.None}
        position={[-0.106, -0.553, -0.237]}
      />
      <mesh
        name="boulder_cell064"
        geometry={nodes.boulder_cell064.geometry}
        material={materials.None}
        position={[-0.338, -0.558, -0.213]}
      />
      <mesh
        name="boulder_cell065"
        geometry={nodes.boulder_cell065.geometry}
        material={materials.None}
        position={[-0.036, -0.209, -0.173]}
      />
      <mesh
        name="boulder_cell066"
        geometry={nodes.boulder_cell066.geometry}
        material={materials.None}
        position={[-0.373, -0.4, -0.215]}
      />
    </group>
  );
}

useGLTF.preload("/models/stone.glb");
